#
#
#server.port=8081
#spring.datasource.url=jdbc:mysql://localhost:3306/productmanagement?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5InnoDBDialect
#
#spring.jpa.hibernate.ddl-auto = update
#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE
#
#
#spring.application.name=Product
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka



#server.port=8080
#spring.datasource.url=jdbc:mysql://localhost:3306/usermanagement?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5InnoDBDialect
#
#spring.jpa.hibernate.ddl-auto = update
#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE


#eureka.client.serviceUrl.defaultZone  = http://localhost:8761/eureka
#eureka.client.instance.preferIpAddress = true
#spring.application.name=usermanagement-service






spring:
  application:
    name: productmanagement
  datasource:
    url: jdbc:mysql://localhost:3306/productmanagement?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
server:
  port: 8084
  
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka